import { useEffect, useState } from "react";

import {
  getTrucks,
  getTruckDecision,
} from "../services/api";

import AIRecommendation from "../components/AIRecommendation";

function AIRecommendations() {
  const [trucks, setTrucks] = useState([]);
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadRecommendations = async () => {
      try {
        const truckData = await getTrucks();

        setTrucks(truckData);

        const results = await Promise.all(
          truckData.map(async (truck) => {
            try {
              return await getTruckDecision(
                truck.truck_id
              );
            } catch (error) {
              console.error(
                `Failed to load AI decision for Truck #${truck.truck_id}:`,
                error
              );

              return null;
            }
          })
        );

        setRecommendations(
          results.filter(Boolean)
        );
      } catch (error) {
        console.error(
          "Failed to load AI recommendations:",
          error
        );
      } finally {
        setLoading(false);
      }
    };

    loadRecommendations();
  }, []);

  return (
    <div className="dashboard">

      <header className="dashboard-header">

        <div>
          <p className="dashboard-label">
            AI FLEET OPTIMIZER
          </p>

          <h1>AI Recommendations</h1>

          <p className="dashboard-subtitle">
            AI-powered fleet and backhaul decision support
          </p>
        </div>

        <div className="system-status">
          <span className="status-dot"></span>
          AI Engine Online
        </div>

      </header>

      {loading ? (
        <div className="loading">
          Loading AI recommendations...
        </div>
      ) : (
        <>
          {/* AI SUMMARY */}

          <section className="kpi-grid">

            <div className="kpi-card">
              <div className="kpi-icon">
                🤖
              </div>

              <div className="kpi-content">
                <p className="kpi-title">
                  Trucks Analyzed
                </p>

                <h2 className="kpi-value">
                  {trucks.length}
                </h2>

                <p className="kpi-description">
                  AI decision analysis
                </p>
              </div>
            </div>

            <div className="kpi-card">
              <div className="kpi-icon">
                🚛
              </div>

              <div className="kpi-content">
                <p className="kpi-title">
                  Recommendations
                </p>

                <h2 className="kpi-value">
                  {recommendations.length}
                </h2>

                <p className="kpi-description">
                  Generated by decision engine
                </p>
              </div>
            </div>

            <div className="kpi-card">
              <div className="kpi-icon">
                📈
              </div>

              <div className="kpi-content">
                <p className="kpi-title">
                  Demand Model
                </p>

                <h2 className="kpi-value">
                  XGBoost
                </h2>

                <p className="kpi-description">
                  Load demand prediction
                </p>
              </div>
            </div>

            <div className="kpi-card">
              <div className="kpi-icon">
                ⏱️
              </div>

              <div className="kpi-content">
                <p className="kpi-title">
                  Waiting Model
                </p>

                <h2 className="kpi-value">
                  Regression
                </h2>

                <p className="kpi-description">
                  Waiting-time prediction
                </p>
              </div>
            </div>

          </section>

          {/* AI RECOMMENDATIONS */}

          <section className="dashboard-section">

            <div className="section-header">

              <div>
                <h2>
                  Truck Recommendations
                </h2>

                <p>
                  Current AI-generated decisions for each truck
                </p>
              </div>

            </div>

            {recommendations.length === 0 ? (

              <div className="no-recommendations">
                No AI recommendations available.
              </div>

            ) : (

              <div className="ai-recommendations-grid">

                {recommendations.map(
                  (recommendation) => (
                    <AIRecommendation
                      key={recommendation.truck_id}
                      recommendation={recommendation}
                    />
                  )
                )}

              </div>

            )}

          </section>

        </>
      )}

    </div>
  );
}

export default AIRecommendations;